CREATE TABLE IF NOT EXISTS BOOK(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title VARCHAR(100) NOT NULL,
    publisher VARCHAR(100) NOT NULL,
    author VARCHAR(100) NOT NULL,
    student_id INTEGER,
    FOREIGN KEY(student_id) REFERENCES STUDENT(id)
);

CREATE TABLE IF NOT EXISTS STUDENT(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(100) NOT NULL,
    phone_no VARCHAR(10) NOT NULL,
    book_id INTEGER,
    FOREIGN KEY (book_id) REFERENCES BOOK(id)
);
