CREATE TABLE IF NOT EXISTS BOOK(
    id INTEGER PRIMARY KEY AUTOINCREMENT, 
    title VARCHAR(100) NOT NULL,
    author VARCHAR(100) NOT NULL,
    publisher VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS STUDENT(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(100) NOT NULL,
    contact VARCHAR(10) NOT NULL,
    roll_no VARCHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS RECORD(
    book_id INTEGER,
    student_id INTEGER,
    FOREIGN KEY("book_id") REFERENCES BOOK(id),
    FOREIGN KEY("student_id") REFERENCES STUDENT(id)
)
